[features]
seeds = false
skip-lint = false
[programs.devnet]
beehubs = "7Q4EY4QVj1o7MyNdzsPed1XYycvgaWmBpnishC8m4yQK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/jjhay/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
